"use client";

import { useEffect, useState } from "react";
import { Sparkles, RefreshCw, AlertCircle } from "lucide-react";

type ForecastData = {
  forecast: string;
  generatedAt: string;
  dateKey: string;
  conditions: {
    tuckCfs: number | null;
    tuckTempF: number | null;
    nantCfs: number | null;
    airTempF: number | null;
    shortForecast: string | null;
  };
  error?: string;
};

function formatTime(iso: string): string {
  try {
    return new Date(iso).toLocaleString("en-US", {
      month: "short", day: "numeric", hour: "numeric", minute: "2-digit",
      timeZone: "America/New_York", timeZoneName: "short",
    });
  } catch {
    return iso;
  }
}

export function ForecastWidget() {
  const [data, setData] = useState<ForecastData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/fishing-forecast");
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const json = await res.json() as ForecastData;
      if (json.error && !json.forecast) throw new Error(json.error);
      setData(json);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to load forecast");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { void load(); }, []);

  return (
    <section className="py-24 bg-primary text-primary-foreground" id="forecast">
      <div className="max-w-3xl mx-auto px-6">
        <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 mb-8">
          <div>
            <div className="flex items-center gap-2 mb-3">
              <Sparkles size={14} className="text-primary-foreground/60" />
              <p className="text-xs font-medium uppercase tracking-[0.25em] text-primary-foreground/60">AI-Generated · Updated Daily at 6am ET</p>
            </div>
            <h2 className="font-serif text-3xl md:text-4xl font-bold text-primary-foreground leading-tight">
              Today&apos;s Fishing Forecast
              <span className="block text-xl md:text-2xl font-normal text-primary-foreground/70 mt-1">
                Generated from 40 Years of On-Stream Data
              </span>
            </h2>
          </div>
          {!loading && (
            <button
              onClick={() => { void load(); }}
              className="flex items-center gap-1.5 text-xs text-primary-foreground/60 hover:text-primary-foreground transition-colors shrink-0"
              aria-label="Refresh forecast"
            >
              <RefreshCw size={12} />
              Refresh
            </button>
          )}
        </div>

        {loading && (
          <div className="space-y-3 animate-pulse">
            <div className="h-4 bg-primary-foreground/10 rounded w-full" />
            <div className="h-4 bg-primary-foreground/10 rounded w-11/12" />
            <div className="h-4 bg-primary-foreground/10 rounded w-full" />
            <div className="h-4 bg-primary-foreground/10 rounded w-4/5" />
            <div className="h-4 bg-primary-foreground/10 rounded w-full mt-6" />
            <div className="h-4 bg-primary-foreground/10 rounded w-10/12" />
            <div className="h-4 bg-primary-foreground/10 rounded w-11/12" />
          </div>
        )}

        {error && !loading && (
          <div className="flex gap-3 bg-primary-foreground/10 border border-primary-foreground/20 px-5 py-4 rounded-sm">
            <AlertCircle size={15} className="shrink-0 mt-0.5 text-primary-foreground/60" />
            <div>
              <p className="text-sm text-primary-foreground/80">Forecast temporarily unavailable.</p>
              <button onClick={() => { void load(); }} className="text-xs text-primary-foreground/60 underline mt-1 hover:text-primary-foreground">
                Try again
              </button>
            </div>
          </div>
        )}

        {data && !loading && (
          <>
            <div className="space-y-5 text-primary-foreground/85 leading-relaxed">
              {data.forecast.split(/\n\n+/).map((para, i) => (
                <p key={i} className="text-[1.05rem]">{para}</p>
              ))}
            </div>

            {data.generatedAt && (
              <p className="mt-8 text-xs text-primary-foreground/40">
                Forecast generated {formatTime(data.generatedAt)}
              </p>
            )}
          </>
        )}

        <div className="mt-8 pt-6 border-t border-primary-foreground/20">
          <p className="text-xs text-primary-foreground/50 leading-relaxed italic">
            This forecast is generated by AI using historical on-stream data collected by Mac Brown Fly Fish since 1987. Conditions change rapidly in mountain environments — always check current USGS flows and water temperatures before heading out.
          </p>
        </div>
      </div>
    </section>
  );
}
